import * as React from "react"

const MOBILE_BREAKPOINT = 768

function subscribe(onChange: () => void) {
  const mql = window.matchMedia(`(max-width: ${MOBILE_BREAKPOINT - 1}px)`)
  mql.addEventListener("change", onChange)
  return () => mql.removeEventListener("change", onChange)
}

/**
 * Generated by `shadcn add sidebar`, rewritten to read the media query through
 * `useSyncExternalStore` instead of mirroring it into state from an effect —
 * the original tripped `react-hooks/set-state-in-effect`, which this project
 * lints as an error. Same API: false until proven mobile, so the server and the
 * first client render agree.
 */
export function useIsMobile() {
  return React.useSyncExternalStore(
    subscribe,
    () => window.innerWidth < MOBILE_BREAKPOINT,
    () => false,
  )
}
