-- AI SMS chatbot (PRD section 5), step 7.
--
-- Two settings columns and one table. Nothing here sends anything — the table
-- exists specifically so the chatbot can run against real inbound traffic
-- without touching Twilio.

-- ---------------------------------------------------------------------------
-- settings
-- ---------------------------------------------------------------------------

alter table public.settings
  -- off   — the engine never calls Claude.
  -- draft — it generates a reply and stores it in ai_drafts. Nothing is sent.
  -- live  — the reply goes out over SMS.
  --
  -- Defaults to 'off', and the default matters: this column is added to a row
  -- that already exists, so the feature arrives switched off on a database
  -- that is already handling real leads.
  add column ai_mode text not null default 'off'
    constraint settings_ai_mode_check
    check (ai_mode in ('off', 'draft', 'live')),

  -- Constrained rather than free text, matching how every other enum-ish
  -- column in this schema is written. A typo'd model reaches the Anthropic API
  -- as a 404 at the worst possible moment — mid-conversation with a lead — so
  -- it is worth one migration per model added.
  add column ai_model text not null default 'claude-sonnet-5'
    constraint settings_ai_model_check
    check (ai_model in (
      'claude-sonnet-5',
      'claude-opus-4-8',
      'claude-haiku-4-5-20251001'
    ));

comment on column public.settings.ai_mode is
  'off | draft | live — draft generates without sending (PRD 5 shadow mode).';
comment on column public.settings.ai_model is
  'Anthropic model id. Adding an option needs a migration (see settings_ai_model_check).';

-- ---------------------------------------------------------------------------
-- ai_drafts
-- ---------------------------------------------------------------------------
--
-- A reply the AI produced but did not send.
--
-- Deliberately not a row in `messages`: every row there is backed by a Twilio
-- SID and means "this reached the contact". A draft sitting in the thread
-- looking like a sent message is exactly the confusion this feature exists to
-- avoid.

create table public.ai_drafts (
  id            uuid primary key default gen_random_uuid(),
  contact_id    uuid not null references public.contacts (id) on delete cascade,

  -- The inbound message this answers. Null for a preview generated by hand
  -- from the dashboard, which answers the thread as it stands rather than one
  -- particular message. SET NULL so a deleted message doesn't take the draft
  -- with it — the draft is still evidence of what the model would have said.
  message_id    uuid references public.messages (id) on delete set null,

  body          text not null,

  -- The model's own signal that a human should take over (PRD 5). In live
  -- mode this is what flips contacts.ai_enabled to false.
  needs_human   boolean not null default false,

  model         text not null,

  -- shadow  — generated automatically because ai_mode was 'draft'.
  -- preview  — generated on demand from the dashboard.
  source        text not null
                  constraint ai_drafts_source_check
                  check (source in ('shadow', 'preview')),

  input_tokens  integer constraint ai_drafts_input_tokens_check
                  check (input_tokens is null or input_tokens >= 0),
  output_tokens integer constraint ai_drafts_output_tokens_check
                  check (output_tokens is null or output_tokens >= 0),

  created_at    timestamptz not null default now()
);

comment on column public.ai_drafts.source is 'shadow | preview';
comment on column public.ai_drafts.needs_human is
  'Model asked for a human. Flips contacts.ai_enabled off once mode is live.';

-- Serves the Inbox, which reads the newest draft for a contact.
create index ai_drafts_contact_id_created_at_idx
  on public.ai_drafts (contact_id, created_at desc);

-- One shadow draft per inbound message. The SMS webhook already dedupes on
-- Twilio's MessageSid, so this is a backstop rather than the primary defence —
-- it stops a re-run of the same message billing a second Claude call and
-- leaving two drafts that disagree with each other.
create unique index ai_drafts_message_id_idx
  on public.ai_drafts (message_id)
  where message_id is not null;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.ai_drafts enable row level security;

create policy "authenticated full access" on public.ai_drafts
  for all to authenticated using (true) with check (true);

-- Stated explicitly rather than trusted to defaults, matching 20260809000000.
revoke all on public.ai_drafts from anon;
